<?php
define("T_CONFIG", "config");
define("T_LANGS", "langs");
define("T_USERS", "users");
define("T_SESSIONS", "sessions");
define("T_TERMS", "terms");
define("T_FOLLOWERS", "followers");
define("T_NOTIFICATION", "notifications");
define("T_SONGS", "songs");
define("T_LIKES", "likes");
define("T_BLOG_LIKES", "blog_likes");
define("T_DISLIKES", "dislikes");
define("T_VIEWS", "views");
define("T_COMMENTS", "comments");
define("T_BLOG_COMMENTS", "blog_comments");
define("T_CATEGORIES", "categories");
define("T_PURCHAES", "purchases");
define("T_FOV", "favorites");
define("T_ARTIST_R", "artist_requests");
define("T_ACTIVITIES", "activities");
define("T_PLAYLISTS", "playlists");
define("T_PLAYLIST_SONGS", "playlist_songs");
define("T_DOWNLOADS", "downloads");
define("T_BLOCKS", "blocks");
define("T_ALBUMS", "albums");
define("T_COPYRIGHTS", "copyrights");
define("T_REPORTS", "reports");
define('T_MESSAGES', 'messages');
define('T_CHATS', 'conversations');
define('T_ADS', 'site_ads');
define('T_SONG_PRICE', 'song_price');
define('T_SEARCHES', 'searches');
define('T_USER_INTEREST', 'user_interest');
define('T_ANNOUNCEMENTS', 'announcement');
define('T_ANNOUNCEMENT_VIEWS', 'announcement_views');
define('T_BANNED_IPS','banned_ip');
define('T_WITHDRAWAL_REQUESTS', 'withdrawal_requests');
define("T_PAYMENTS", "payments");
define('T_APP_SESSIONS', 'apps_sessions');
define('T_BANK_RECEIPTS', 'bank_receipts');
define('T_BLOG', 'blog');
define('T_USR_ADS', 'user_ads');
define('T_ADS_TRANS', 'ads_transactions');
define('T_REVIEWS', 'reviews');
define('T_FIELDS', 'profile_fields');
define('T_USERS_FIELDS', 'user_fields');
define('T_INVITATIONS', 'admin_invitations');
define('T_STATIONS','stations');
define('T_CUSTOM_PAGES','custompages');
define('T_COMMENT_REPLIES', 'comment_replies');
define('T_POINT_SYSTEM', 'point_system');
define('T_BAD_LOGIN', 'bad_login');
define('T_ARTISTS_TAGS', 'artists_tags');
?>